--- #YAML:1.0
name:               Catalyst-Controller-WrapModPerl
version:            0.001
abstract:           Perl extension for blah blah blah
author:
    - Robin Edwards <robin.ge@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::ApacheFormat:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
